spring:
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: 123456
  # 数据源
  datasource:
    url: jdbc:postgresql://localhost:5432/pms
    username: postgres
    password: 6755
    driver-class-name: org.postgresql.Driver


  # 本地缓存
  redis:
    host: 127.0.0.1
    port: 6379
    password: 6755
    timeout: 0
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.pms.api.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#debug: true
logging:
  file: D:/log/log.log

#端口和根路径
server:
  port: 8000
  servlet:
    context-path: /
