spring:
#  profiles:
#    active: dev
  security:
    user:
      name: admin
      password: 123456
  datasource:
    url: jdbc:postgresql://localhost:5432/pms
    username: postgres
    password: 6755
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.pms.api.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#debug: true
logging:
  file: D:/log/log.log

pms:
  url: http://localhost:3000
  apiurl: http://localhost:8000

server:
  port: 8000
  servlet:
    context-path: /
